<?php
/**
 * @file
 * Code for the GSB Feature Program Panelized Page CT feature.
 */

include_once 'gsb_feature_program_panelized_page_ct.features.inc';

function gsb_feature_program_panelized_page_ct_page_alter(&$page) {
  if ($page['#type'] == 'page') {
    $node = menu_get_object();
    if ($node && $node->type == 'program_panelized_page') {
      $found = false;
      $alias = $node->path['alias'];
      $alias = explode('/', $alias);
      $ppp_page_type = $alias[count($alias)-1];
      if ($ppp_page_type == 'curriculum') {
        drupal_set_title('Curriculum');
        $found = true;
      }
      else if ($ppp_page_type == 'faculty') {
        drupal_set_title('');
        $found = true;
      }
      else if ($ppp_page_type == 'participant-profile') {
        drupal_set_title('Participant Profile');
        $found = true;
      }
      else {
        drupal_set_title($node->title);
      }
      if ($found) {
        $title = $page['content']['metatags']['node:program_panelized_page']['title']['#attached']['metatag_set_preprocess_variable'][0][2];
        $title = str_replace('--- curriculum', '', $title);
        $title = str_replace('--- faculty', '', $title);
        $title = str_replace('--- participant', '', $title);
        $page['content']['metatags']['node:program_panelized_page']['title']['#attached']['metatag_set_preprocess_variable'][0][2] = $title;
      }
    }
  }
}
